### ISSUE TITLE
New `Release Type ` attribute for Releases

### ISSUE THREAD

**Issue by arunazhakesan** [eclipse-sw360/sw360#1374]
**Background**

At present the releases created against a component inherits the Component Type info from the component creation page (OSS/COTS etc.) There is no further data that is passed on to the Release level to identify the "Type of Release" : Binary Release or Source Release 

Binary Release - is defined as any binary package that is downloaded from a package manager. This is the artifact that is used by the development team for project requirements. The corresponding sources for these binary packages are not downloaded or saved by the project team in any repository. The source files are required to be collected and uploaded in SW360 for component clearing purpose.  Cyclone DX and ORT package manifest provides the link to the source repo corresponding to each binary packages.

Source Release -  is defined as any source package that is maintained by the community in any public repository (GIT), from where it is used to build binary packages. The complete and corresponding source code is required for clearing purposes. The clearing team prepares a report against the clearing of a source package and not for each binary package.

**How SW360 processes Binary and source Release now?**

	1. Both binary and source release is processed in the same way. No differentiation in terms of type
	2. This creates redundant information when the "linked Releases' feature is used.
	3. This results in the need to have all artifacts to be same for both binary and source releases

**Proposal**

To introduce a new field; `Release Type` in SW360.
Values - 
	1. Binary Release
	2. Source Release

		○ Can be configured at the time of creating a release manually or via automation.
		○ Releases can be linked only based on the following relationship/hierarchy type

                                -  Multiple Binary Releases can only be linked to a Single Source Release
                                -  Binary Release cannot have any other Binary releases linked to it
                                -  Source releases can be linked to multiple  Binary releases

**Comment by shi9qiu** [comment]
In my opinion, @arunazhakesan 's idea may be a better choice. It may make the system more complicated but does solve the problems.
Or we can set the binary release as a new type of entity and design a new set of attributions and the related API for it. In this way, we don't need to fix all API and the display.

**Comment by sameer1046** [comment]
The link between releases is an already existing feature of sw360. Just to extend that, if the linked child release inherits the parent clearing state, then this problem will be solved without major change in sw360 codebase.
Just to add another field "release type" in release details tab.

**Comment by JaideepPalit** [comment]
From internal discussion

![image](https://user-images.githubusercontent.com/56534710/147064915-ce7e8a82-aa1e-4794-9d95-b2c0cc233087.png)

**Comment by shi9qiu** [comment]
The diagram looks nice!
But I am still confused about something. Could you kindly tell me what is the difference between the green project and the light green project? Why the direction of their arrow linking to the package is reversed?
And I am also confused about what the word "new" in "New Package 8" means.
Thank you!

**Comment by JaideepPalit** [comment]
> The diagram looks nice! But I am still confused about something. Could you kindly tell me what is the difference between the green project and the light green project? Why the direction of their arrow linking to the package is reversed?

  - It is an error in diagram. There is no difference , both are same, 

 > And I am also confused about what the word "new" in "New Package 8" means. Thank you!

  - There is no special meaning, both are same. It was used to discuss some scenarios
