### ISSUE TITLE
New function for Department Management

### ISSUE THREAD

**Issue by quan-tv** [eclipse-sw360/sw360#1439]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

SW360 allows user belong to multiple department. But although there is function for User Management, the function for Department Management is not available yet.

I think that it would be nice if we implement function for Department Management.

There are two points I would like to remark - I am not sure that the matter of Toshiba only, or other companies also are sharing the same thing:
- There are many departments, and it would be good if departments and their members can be created/assigned automatically based on information from input files (Excel/CSV) via a kind of scheduled job.
- All members will have the same fixed 'Primary Department', so in the context of this new function, we allow to assign Secondary Departments only. Default Role will be 'User'.

#### Screenshots

Here is my ideal for this function.

1. Add new item in Admin menu:
![image](https://user-images.githubusercontent.com/85483077/146902118-4170bff1-6769-435d-a877-a1605db4700b.png)

2. Click the new menu item to open screen 'Department List'
![image](https://user-images.githubusercontent.com/85483077/146902201-3b10e6cd-7b59-444d-b97e-e2a68540e543.png)

3. Screen design for Department Edit
![image](https://user-images.githubusercontent.com/85483077/146902453-b5471c06-6bb2-4643-95c1-c052b59c29d4.png)

4. How data is stored in DB: 
I noticed that in the design of current table 'User', database 'sw360users', the field 'secondaryDepartmentsAndRoles' is ready for this new function. Here is one sample:
![image](https://user-images.githubusercontent.com/85483077/146910245-aedca8a2-fa64-410f-aa14-b741b43f2702.png)

**Comment by tienlee** [comment]
I would like to share the demo.
[SW360-20220406 - Demo1439.pptx](https://github.com/eclipse/sw360/files/8440283/SW360-20220406.-.Demo1439.pptx)

**Comment by KoukiHama** [comment]
Please check these file  which  @tienlee  made
https://github.com/eclipse/sw360/files/8440283/SW360-20220406.-.Demo1439.pptx
