### ISSUE TITLE
Can not load component page when additional data's text too long.

### ISSUE THREAD

**Issue by hoangnt2** [eclipse-sw360/sw360#1772]
### How to reproduce
1. Edit a component. Then add an additional data with long text. Example: TestValueeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/94659621/208370913-40b66a3a-9f6d-482c-a22d-30d154c8ec90.png)
2. Click update component. Component detail page can not be loaded 
![image](https://user-images.githubusercontent.com/94659621/208371568-5f79b33e-1010-40a6-a2ea-9c2fd475c603.png)

### Expect: 
Component detail page can load normally and additional data will be displayed as below.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/94659621/208372278-7727282b-8e08-4ea1-bc10-b91a2bb87506.png)

### Versions

* Last commit id on master: 0837f7a
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by rudra-superrr** [comment]
Testing was successful.

![image](https://user-images.githubusercontent.com/58290634/208868071-23d1fcaa-0893-4b57-a119-3569bd6556cb.png)

**Comment by rudra-superrr** [comment]
One thing I want to add, maximum length allowed for a word in additional data's value is 29 letters.
If additional data's value exceeds 29 letters for a word then additional data won't be displayed.

In the below ss value for key(keyyy) exceeds 29 letters.
![image](https://user-images.githubusercontent.com/58290634/208871097-b6660467-7ad4-4236-98eb-aaa1e89cb386.png)

![image](https://user-images.githubusercontent.com/58290634/208871218-721aabe4-ab7e-4a92-99a5-a531860784a9.png)
