### ISSUE TITLE
Search page can not show result with single quote character and can not search obligation.

### ISSUE THREAD

**Issue by hoangnt2** [eclipse-sw360/sw360#1774]
### Description
1. If search result have single quote character, search page can not load search result.
2. Obligation can not be searched in search page.

##### Bug No 1:  If search result have single quote character, search page can not load search result.
1. Have more than one licenses with single quote character in short name.
![image](https://user-images.githubusercontent.com/94659621/208374336-2f0bf299-0a14-402d-8dad-84d8ad16af30.png)
2. Go to search page. Enter name of that license and select **Licenses** check box then click search button. Search result can not be load as below.
![image](https://user-images.githubusercontent.com/94659621/208375108-d5570ea1-f491-40a7-9156-16322f3485c9.png)

- Expect: Can show search result.

##### Bug No 2:  Obligation can not be searched in search page.
- Pre-condition: Have some obligations in database.
1. Enter name of one obligation in search page and select **Obligations** check box then click search button. Search result table always show _No data available in table_ 
![image](https://user-images.githubusercontent.com/94659621/208376238-8ecf03a0-b230-4629-becb-81ce525916a7.png)

- Expect: Can show obligations match with search condition.

### Versions

* Last commit id on master: 0837f7a
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by smrutis1** [comment]
It would look good, if one icon can be added in type for obligation.

![image](https://user-images.githubusercontent.com/46560890/213428498-7d7793a2-a99a-4ef6-b24f-e6a725898347.png)

**Comment by hoangnt2** [comment]
> It would look good, if one icon can be added in type for obligation.
> 
> ![image](https://user-images.githubusercontent.com/46560890/213428498-7d7793a2-a99a-4ef6-b24f-e6a725898347.png)

![image](https://user-images.githubusercontent.com/94659621/215386846-3e8d8ce3-85d9-41bb-9853-53f11cb37bf4.png)
I have added Obligation icon to type column. Thanks for your comment.
