### ISSUE TITLE
Recent docker setup: use of "slim war" conceptually broken/risky

### ISSUE THREAD

**Issue by ljaenicke** [eclipse-sw360/sw360#1808]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

The "create-slim-war-files.sh" script copies all jar files being part of the wars to a shared repository. As the versions of the packages are not synchronized, several versions of the same package may end up in the directory. As tomcat only loads one version of a package and ignores the others, this leads to more or less obvious failures.

#### How to reproduce

The duplication of commons-io in versions 1 and two leads to failure of the fossolgy component due to
  java.lang.NoSuchMethodError: long org.apache.commons.io.IOUtils.copyLarge
with copyLarge not being part of commons-io 1. (Result: on startup the fossology backend fails and the first login is stalled until timeout after 10 minutes)
(This is how I finally debugged the issue.)

Also most of the functions might fail with an "Unable to find user", I however do not know which confllict might be causing this behavior. In any case couchdb does not see traffic during operation with the "sim-war" setup.

List of packages, some duplicates may be the cause of errors, some may be non-critical.

accessors-smart-2.4.8.jar
activation-1.1.1.jar
activation-1.1.jar
annotations-1.3.2.jar
annotations-15.0.jar
apache-mime4j-core-0.7.2.jar
apache-mime4j-dom-0.7.2.jar
asm-9.1.jar
asm-debug-all-4.1.jar
aspectjrt-1.8.0.jar
bcmail-jdk15-1.45.jar
bcpkix-jdk15on-1.64.jar
bcprov-jdk15-1.45.jar
bcprov-jdk15on-1.64.jar
boilerpipe-1.1.0.jar
btf-1.3.jar
build-configuration-17.0.0-SNAPSHOT.jar
byte-buddy-1.12.13.jar
checker-qual-3.12.0.jar
cloudant-client-2.19.1.jar
cloudant-http-2.19.1.jar
collection-0.7.jar
commonIO-17.0.0-SNAPSHOT.jar
commons-beanutils-1.7.0.jar
commons-beanutils-1.9.4.jar
commons-beanutils-core-1.8.0.jar
commons-cli-1.4.jar
commons-codec-1.15.jar
commons-codec-1.5.jar
commons-collections-3.2.1.jar
commons-collections-3.2.2.jar
commons-collections4-4.4.jar
commons-compress-1.21.jar
commons-compress-1.8.1.jar
commons-configuration-1.6.jar
commons-csv-1.9.0.jar
commons-digester-1.8.jar
commons-digester3-3.2.jar
commons-httpclient-3.1.jar
commons-io-1.4.jar
commons-io-2.11.0.jar
commons-lang-2.4.jar
commons-lang3-3.12.0.jar
commons-logging-1.1.1.jar
commons-logging-1.2.jar
commons-math3-3.6.1.jar
commons-text-1.9.jar
curvesapi-1.06.jar
datahandler-17.0.0-SNAPSHOT.jar
ektorplucene-0.2.0.jar
error_prone_annotations-2.11.0.jar
evo-inflector-1.3.jar
exporters-17.0.0-SNAPSHOT.jar
failureaccess-1.0.1.jar
FastInfoset-1.2.16.jar
findbugs-annotations-1.3.9-1.jar
fontbox-1.8.6.jar
gson-2.8.9.jar
guava-31.1-jre.jar
HdrHistogram-2.1.12.jar
httpclient-4.0.1.jar
httpclient-4.5.14.jar
httpclient-cache-4.3.jar
httpclient-cache-4.5.13.jar
httpcore-4.0.1.jar
httpcore-4.4.8.jar
isoparser-1.0.2.jar
istack-commons-runtime-3.0.8.jar
j2objc-annotations-1.3.jar
jackson-annotations-2.13.4.jar
jackson-core-2.13.4.jar
jackson-coreutils-2.0.jar
jackson-coreutils-equivalence-1.0.jar
jackson-databind-2.13.4.2.jar
jackson-dataformat-xml-2.12.2.jar
jackson-dataformat-yaml-2.12.3.jar
jackson-datatype-jdk8-2.13.2.jar
jackson-datatype-jsr310-2.13.2.jar
jackson-module-jaxb-annotations-2.12.2.jar
jackson-module-parameter-names-2.13.2.jar
jakarta.activation-api-1.2.1.jar
jakarta.activation-api-1.2.2.jar
jakarta.annotation-api-1.3.5.jar
jakarta.json-2.0.1.jar
jakarta.xml.bind-api-2.3.2.jar
java-libpst-0.8.1.jar
java-spdx-library-1.1.0.jar
javax.activation-api-1.2.0.jar
javax.annotation-api-1.3.2.jar
javax.servlet-api-3.1.0.jar
jaxb-api-2.3.1.jar
jaxb-runtime-2.3.2.jar
jcip-annotations-1.0.jar
jcl-over-slf4j-1.6.4.jar
jcl-over-slf4j-1.7.36.jar
jdom-1.0.jar
jempbox-1.8.6.jar
jena-arq-4.2.0.jar
jena-base-4.2.0.jar
jena-core-4.2.0.jar
jena-iri-4.2.0.jar
jena-shaded-guava-4.2.0.jar
jetty-continuation-9.3.9.v20160517.jar
jetty-http-9.3.9.v20160517.jar
jetty-io-9.3.9.v20160517.jar
jetty-security-9.3.9.v20160517.jar
jetty-server-9.3.9.v20160517.jar
jetty-servlet-9.3.9.v20160517.jar
jetty-servlets-9.3.9.v20160517.jar
jetty-util-9.3.9.v20160517.jar
jhighlight-1.0.jar
jinterface-1.5.3.2.jar
jmatio-1.0.jar
joda-time-1.6.2.jar
jopt-simple-5.0.4.jar
jose4j-0.7.9.jar
jsch-0.1.54.jar
json-20090211.jar
json-20190722.jar
jsonld-java-0.13.3.jar
json-path-2.6.0.jar
json-schema-core-1.2.14.jar
json-schema-validator-2.2.14.jar
json-simple-1.1.1.jar
json-simple-2.3.1.jar
json-smart-2.4.8.jar
jsoup-1.14.2.jar
jsr305-3.0.2.jar
juniversalchardet-1.0.3.jar
LatencyUtils-2.0.3.jar
libphonenumber-8.11.1.jar
libthrift-0.16.0.jar
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
log4j-1.2.14.jar
log4j-1.2-api-2.17.1.jar
log4j-api-2.17.1.jar
log4j-core-2.17.1.jar
log4j-jcl-2.17.1.jar
log4j-slf4j-impl-2.17.1.jar
lombok-1.18.24.jar
lucene-analyzers-common-6.4.1.jar
lucene-analyzers-smartcn-6.4.1.jar
lucene-core-6.4.1.jar
lucene-highlighter-6.4.1.jar
lucene-join-6.4.1.jar
lucene-memory-6.4.1.jar
lucene-queries-6.4.1.jar
lucene-queryparser-6.4.1.jar
lucene-sandbox-6.4.1.jar
mail-1.4.7.jar
mailapi-1.6.2.jar
metadata-extractor-2.6.2.jar
micrometer-core-1.8.4.jar
msg-simple-1.2.jar
netcdf-4.2.20.jar
ooxml-schemas-1.1.jar
opencsv-5.5.2.jar
org.ektorp-1.5.0.jar
pdfbox-1.8.6.jar
poi-3.11-beta2.jar
poi-4.1.2.jar
poi-ooxml-3.11-beta2.jar
poi-ooxml-4.1.2.jar
poi-ooxml-schemas-3.11-beta2.jar
poi-ooxml-schemas-4.1.2.jar
poi-scratchpad-3.11-beta2.jar
rest-common-17.0.0-SNAPSHOT.jar
rhino-1.7.7.2.jar
rhino-1.7R4.jar
rome-1.0.jar
saxon-8.7.jar
saxon-dom-8.7.jar
slf4j-api-1.7.30.jar
slf4j-api-1.7.5.jar
slf4j-log4j12-1.7.5.jar
snakeyaml-1.27.jar
snakeyaml-1.29.jar
SparseBitSet-1.2.jar
spdx-jackson-store-1.1.0.jar
spdx-rdf-store-1.1.0.jar
spdx-spreadsheet-store-1.1.0.jar
spdx-tagvalue-store-1.1.0.jar
spring-aop-5.3.18.jar
spring-aop-5.3.19.jar
spring-beans-5.3.18.jar
spring-beans-5.3.19.jar
spring-boot-2.6.6.jar
spring-boot-actuator-2.6.6.jar
spring-boot-actuator-autoconfigure-2.6.6.jar
spring-boot-autoconfigure-2.6.6.jar
spring-boot-devtools-2.6.6.jar
spring-boot-starter-2.6.6.jar
spring-boot-starter-actuator-2.6.6.jar
spring-boot-starter-data-rest-2.6.6.jar
spring-boot-starter-json-2.6.6.jar
spring-boot-starter-security-2.6.6.jar
spring-boot-starter-web-2.6.6.jar
spring-context-5.3.18.jar
spring-context-5.3.19.jar
spring-core-5.3.18.jar
spring-core-5.3.19.jar
spring-data-commons-2.6.3.jar
spring-data-rest-core-3.6.3.jar
spring-data-rest-hal-explorer-3.6.3.jar
spring-data-rest-webmvc-3.6.3.jar
spring-expression-5.3.18.jar
spring-expression-5.3.19.jar
spring-hateoas-1.4.1.jar
spring-jcl-5.3.18.jar
spring-jcl-5.3.19.jar
spring-plugin-core-2.0.0.RELEASE.jar
spring-security-config-5.6.2.jar
spring-security-core-5.6.2.jar
spring-security-crypto-5.6.2.jar
spring-security-jwt-1.1.1.RELEASE.jar
spring-security-oauth2-2.5.1.RELEASE.jar
spring-security-oauth2-autoconfigure-2.6.6.jar
spring-security-web-5.6.2.jar
spring-tx-5.3.18.jar
spring-web-5.3.18.jar
spring-web-5.3.19.jar
spring-webmvc-5.3.18.jar
spring-webmvc-5.3.19.jar
src-attachments-17.0.0-SNAPSHOT.jar
src-changelogs-17.0.0-SNAPSHOT.jar
src-common-17.0.0-SNAPSHOT.jar
src-components-17.0.0-SNAPSHOT.jar
src-cvesearch-17.0.0-SNAPSHOT.jar
src-fossology-17.0.0-SNAPSHOT.jar
src-health-17.0.0-SNAPSHOT.jar
src-licenseinfo-17.0.0-SNAPSHOT.jar
src-licenses-17.0.0-SNAPSHOT.jar
src-moderation-17.0.0-SNAPSHOT.jar
src-projects-17.0.0-SNAPSHOT.jar
src-schedule-17.0.0-SNAPSHOT.jar
src-search-17.0.0-SNAPSHOT.jar
src-users-17.0.0-SNAPSHOT.jar
src-vendors-17.0.0-SNAPSHOT.jar
src-vulnerabilities-17.0.0-SNAPSHOT.jar
src-wsimport-17.0.0-SNAPSHOT.jar
stax2-api-4.2.1.jar
stax-api-1.0.1.jar
stax-ex-1.8.1.jar
svc-common-17.0.0-SNAPSHOT.jar
tagsoup-1.2.1.jar
tika-core-1.6.jar
tika-parsers-1.6.jar
titanium-json-ld-1.1.0.jar
tools-java-1.1.0.jar
txw2-2.3.6.jar
unidataCommon-4.2.20.jar
uri-template-0.10.jar
velocity-engine-core-2.3.jar
velocity-tools-generic-3.1.jar
vorbis-java-core-0.6.jar
vorbis-java-tika-0.6.jar
woodstox-core-6.2.4.jar
xercesImpl-2.8.1.jar
xml-apis-1.3.03.jar
xmlbeans-2.3.0.jar
xmlbeans-3.1.0.jar
xmlschema-core-2.2.5.jar
xmpcore-5.1.2.jar
xz-1.5.jar

(Logs may be reproduced if needed)

### Possible solutions

The problems went away after removing the "slim-war" process and using fat wars (on the price of disk space and memory, I had to increase memory settings for tomcat).

The duplicates might go away after synchronizing all packages. This may however be a tedious task as dependencies might be indirect. And the issue might re-appear after updating some components and not enforcing synchronization.

Finally the create-slim-war-files.sh might be extended to not create such duplicates by checking the packages and only share those that do not conflict. I could however not easily create such mechanism in shell script.

**Comment by ljaenicke** [comment]
I tried various combinations to create slim-wars without duplicate packages included. I simply did not get it to work. May be it might be possible by perforrming a complete analysis of all dependencies, maybe not.
In any case side effects might be created that are not caught in some tests but only occur in specific applications.
To reproduce the basic issue described, just build a fresh docker installation from an actual version, then perform the "docker compose up". The startup procdure will hang in the fossology component. It will take the default timeout of 10 minutes to detect that there is no fossology backend available. Only then the system will react to the http://localhost:8080 address.

If the slim-war setup is removed, the resources needed will increase significantly (in fact it more or less overloaded my old development system and the new one was only provided recently :-)). But SW360 will start up as expected.

**Comment by heliocastro** [comment]
Hi @ljaenicke
Thanks for the big analysis.

I have two other possibilities that you not covered here ( or at least not socumented ) to test.

1 - Get rid of duplicates. 
When i started the gradle experience, paused to wait to new interface, i started to normalize all dependencies, so the situation that you described above would not happens, and then one version of each can be loaded and tomcat would be happy. ( maybe )
This can be achieved forcing the specific version on the component in main pom.xml. I will do this test myself.

2 - Use shared loading, that we already do but not in totality. This maybe will solve part of the issue, but i sitll think will hit similar issue.

So you think i'm far off or worth try ?

**Comment by ljaenicke** [comment]
I tried to remove duplicates with the patch attached, it however does not make much sense. For tomcat to load the jars, their dependencies need to be present at the time of loading.

[0001-Another-attempt-on-slim-wars.patch](https://github.com/eclipse-sw360/sw360/files/11276312/0001-Another-attempt-on-slim-wars.patch)

**Comment by ljaenicke** [comment]
I also tried to synchronize dependencies, it however turns out that this might be quite difficult for example for clucene-couchdb. At least the latest released version is using really old dependencies. I had a look into using a recent snapshot from git, which might look better. I however do not have any clue about the mechanisms behind it, so even if updating and synchronizing depencies might be done, I don't have any idea on possible side effects.
So I really don't think, this would be a good idea.
[0001-Test-update-CLUCENE_COUCHDB.patch](https://github.com/eclipse-sw360/sw360/files/11276335/0001-Test-update-CLUCENE_COUCHDB.patch)
[0002-Update-thrift-to-latest-version.patch](https://github.com/eclipse-sw360/sw360/files/11276336/0002-Update-thrift-to-latest-version.patch)

**Comment by ljaenicke** [comment]
I never got anything stable or trustworthy enough.
I also reasearched maven mechanisms. There seems to be some ear-plugin that should be able to handle this kind of situation, tomcat however does not support EAR.

**Comment by heliocastro** [comment]
> I tried to remove duplicates with the patch attached, it however does not make much sense. For tomcat to load the jars, their dependencies need to be present at the time of loading.

This approach is not correct as happens after build, so i will cleanup first direct on grep Maven build files, which willnot affect the slim/not slim, but necessary anyway.

**Comment by heliocastro** [comment]
> I also tried to synchronize dependencies, it however turns out that this might be quite difficult for example for clucene-couchdb. At least the latest released version is using really old dependencies. I had a look into using a recent snapshot from git, which might look better. I however do not have any clue about the mechanisms behind it, so even if updating and synchronizing depencies might be done, I don't have any idea on possible side effects.
> So I really don't think, this would be a good idea.

I will look on couchdb component, Is mostly for the search engine, and can be upgraded.
For the thrift, is more delicates. 0.17 break some interfaces and need to be better tested, so no go for now

**Comment by heliocastro** [comment]
@ljaenicke Interesting find about commons-io. I could not track 1.4 from a clean build, mean that couchdb-clucene component can be one of the guilt ones as well.
Excellent find

**Comment by heliocastro** [comment]
@ljaenicke If you have time at some point in near future, please can you try the mentioned pull request above ?

**Comment by arunazhakesan** [comment]
Fixed via PR #1917
