### ISSUE TITLE
Maven version (3.8.7) is outdated and Docker doesn't work

### ISSUE THREAD

**Issue by tienlee** [eclipse-sw360/sw360#1882]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Maven 3.8.7 (https://github.com/eclipse-sw360/sw360/blob/main/.versions) no longer exists at https://dlcdn.apache.org/maven/maven-3/

I tried to upgrade maven version to 3.8.8, and docker works.
We need to upgrade from 3.8.7 to 3.8.8. Please consider this point.

**Comment by heliocastro** [comment]
Pull request merged.
