### ISSUE TITLE
Import of SPDX SBOM

### ISSUE THREAD

**Issue by eschenbachertq** [eclipse-sw360/sw360#1905]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

I would like to import components as well as entire projects via SPDX SBOM into SW360.
As documentation for this feature I have https://www.eclipse.org/sw360/docs/userguide/project/#105-import-sbom as well as https://static.sched.com/hosted_files/ossjapan2022/ed/OSSJapan2022-SW360.pdf used. Can I find more documentation on this somewhere?
I am aware that the OSSJapan2022-SW360.pdf related to the SPDX SBOM is about a future feature (SPDX Document Tab). However, the basic import of an SBOM is also described here and that is exactly what I would like to reproduce in my SW360 system.

### Description

Importing an SBOM at component level only works partially, i.e. only one component is imported. As SBOM https://github.com/spdx/tools-java/blob/master/testResources/SPDXRdfExample-v2.2.spdx.rdf as well as https://github.com/spdx/tools-java/blob/master/testResources/SPDXRdfExample-v2.3.spdx.rdf is used. Only the component glibc and the release "glibc 2.11.1" were created. Neither the component nor its release contain any meta information (e.g. CPE ID, license information, source download URL ...)

#### How to reproduce

1. Download SBOM https://github.com/spdx/tools-java/blob/master/testResources/SPDXRdfExample-v2.2.spdx.rdf OR https://github.com/spdx/tools-java/blob/master/testResources/SPDXRdfExample-v2.3.spdx.rdf
2. Go to Components tab
3. Click on "Import SBOM" and upload SBOM from step 1

#### Screenshots

![image](https://user-images.githubusercontent.com/7579200/231188912-76acdf57-c83a-47cb-a93d-2f319b819754.png)
![image](https://user-images.githubusercontent.com/7579200/231190491-01dfb193-eb99-44cb-abe6-834e3bff5b63.png)
![image](https://user-images.githubusercontent.com/7579200/231189491-3a8dc39f-afc8-4fea-8f72-396c60a5d450.png)

### Versions

* SW360: 17.0.0 (Commit 5243898)
* Operating System (lsb_release -a): Ubuntu 22.04.2 LTS

**Comment by KoukiHama** [comment]
you will import some component after merge this PR 
https://github.com/eclipse-sw360/sw360/pull/1682

**Comment by eschenbachertq** [comment]
Many thanks for the notification. I will test it as soon as possible.
