### ISSUE TITLE
Make the SPDX Parser in SW360 compatible with the new version of SPDX generated for ISR

### ISSUE THREAD

**Issue by afsahsyeda** [eclipse-sw360/sw360#1915]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Currently, the main licenses in ISR are not being captured due to changes in the new version of SPDX.

#### Screenshots

![image](https://user-images.githubusercontent.com/115608771/232999871-14d2f4bd-3cff-4852-bf9b-5f5ed2b247a2.png)

**Comment by KoukiHama** [comment]
it is related to this issue 
https://github.com/eclipse-sw360/sw360/issues/1871

**Comment by afsahsyeda** [comment]
Hi @KoukiHama,

I agree it is similar but this issue is limited to the SPDX generated from Fossology tool.

**Comment by KoukiHama** [comment]
Yes, I think so too, they are similar, but they are not the same. 
I just added a comment to make it easier to see the difference later.
