### ISSUE TITLE
Liferay portlets missing in Docker deployment

### ISSUE THREAD

**Issue by gaurav601** [eclipse-sw360/sw360#1960]
### Description

Using Ubuntu 22.04.2 LTS, I followed the [SW360 guide for Docker deployment](https://www.eclipse.org/sw360/docs/deployment/deploy-docker/) and made it to the end, where I ran `./sw360chores.pl --build -- up`. The portlets do not load, so I cannot use SW360 (see the image below). 

After that, I followed the [main guide here](https://www.eclipse.org/sw360/docs/deployment/nativeinstall/native-install-sw360-version-17.0.0/) to get the Liferay portal working. When I got to the [section about importing LAR files](https://www.eclipse.org/sw360/docs/deployment/nativeinstall/native-install-sw360-version-17.0.0/) to set up SW360. Because my Liferay portal is in version 7.3.3, I used the 7_3_3 LAR files that were provided [here](https://github.com/eclipse-sw360/sw360/tree/main/frontend/configuration) for both public and private pages. Unfortunately, after reaching the end of this guide, the portlets cannot be found (screenshot in below section).

I then closed the project (stopped all containers) and re-ran the project using `./sw360chores.pl --build -- up` and collected log files another day (so the containers already exist, as detected in the logs). Attached are the logs in the terminal output when running that build command, and also another file containing the logs from the main Docker container that has Liferay.

#### How to reproduce

1. Use Ubuntu 22.04.2 LTS.
2. Follow the [guide for Docker deployment](https://www.eclipse.org/sw360/docs/deployment/deploy-docker/) on SW360's main site.
3. Follow the guide to configure the Liferay portal [here](https://www.eclipse.org/sw360/docs/deployment/nativeinstall/native-install-sw360-version-17.0.0/). When you reach the section, "[3.7.2 Configure Liferay Portal](https://www.eclipse.org/sw360/docs/deployment/nativeinstall/native-install-sw360-version-17.0.0/)", follow the instructions while using the `7_3_3` LAR files (found [here](https://github.com/eclipse-sw360/sw360/tree/main/frontend/configuration)) because the Liferay portal is on version 7.3.3.
4. See whether the portlets on the main SW360 page on https://localhost:8443 show up. For me, they could not be found.

#### Screenshots

(1) Portlets cannot be found.
![image](https://github.com/eclipse-sw360/sw360/assets/72317382/65d26749-56cd-4963-b518-b23851494624)

(2) The list of containers that are up when using the command, `./sw360chores.pl --build -- up`.
![image](https://github.com/eclipse-sw360/sw360/assets/72317382/0116c545-56e2-46e7-a990-768df67f40e7)

### Logs

- The file [launch-logs.txt](https://github.com/eclipse-sw360/sw360/files/11481714/launch-logs.txt) is what happens after I run `./sw360chores.pl --build -- up` from the [SW360 Docker deployment guide](https://www.eclipse.org/sw360/docs/deployment/deploy-docker/).
- The file [container-running-logs.txt](https://github.com/eclipse-sw360/sw360/files/11481713/container-running-logs.txt) is the result of `docker logs sw360_sw360` after the Liferay portal was done deploying using the previous step.

**Comment by KoukiHama** [comment]
Hello., sw360chores were archived and no one maintain them now.
If you want to build sw360 by docker or docker-compose, please use and check this doc
https://github.com/eclipse-sw360/sw360/blob/main/README_DOCKER.md
