### ISSUE TITLE
Adding context sensitive help within 

### ISSUE THREAD

**Issue by arunazhakesan** [eclipse-sw360/sw360#2021]
**Background**
At present, the documentation is available in an external website. The user needs to specifically navigate to the website page and then search for the desired help topic  from the user guide. This is not very helpful to the user when they search for help on specific topic during the workflow.

**Proposal**
As the documentation source files are available as `.md` files, it would be useful to add the corresponding content files to the specific topics in the SW360 UI itself. This will help the user to click the help document from within the UI itself. 

A new button can be created and the corresponding `.md` file can be linked to it. The user can click the button to open the page.

<img width="946" alt="image" src="https://github.com/eclipse-sw360/sw360/assets/40492961/488debdc-fc3e-4a76-9cf0-81fb4dafa7e2">

**Comment by heliocastro** [comment]
I would draw a hard line here 
For the new interface is feasible, for the current liferay one is a no-go due the complexity. 
An alternative solution is providw the documentation site that is static with the release.

**Comment by arunazhakesan** [comment]
Not feasible. Hence closing
