### ISSUE TITLE
Build Test failed sw360 in local and Github Action

### ISSUE THREAD

**Issue by tuannn2** [eclipse-sw360/sw360#2026]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Build Test failed sw360 (branch: main) in local and Github Action
#### How to reproduce
Command line to Build: 
```
mvn clean package -P deploy -Dbase.deploy.dir=. -Dliferay.deploy.dir=${LIFERAY_INSTALL}/deploy -Dbackend.deploy.dir=${LIFERAY_INSTALL}/tomcat-9.0.56/webapps -Drest.deploy.dir=${LIFERAY_INSTALL}/tomcat-9.0.56/webapps -Dtest=org/eclipse/sw360/rest/resourceserver/restdocs/* -Dhelp-docs=true -Dsurefire.failIfNoSpecifiedTests=false
``` 
Result: 
![LocalGithubAction](https://github.com/eclipse-sw360/sw360/assets/94596393/26cd2290-e598-4ad4-832f-2fe1493b2d1b)

![GithubAction](https://github.com/eclipse-sw360/sw360/assets/94596393/4cf9c46e-a12a-4a8c-a7ad-5d6e2e7b1032)

**Comment by ag4ums** [comment]
Interestingly this is not happening in github CI, but seems its failing with testcases

**Comment by heliocastro** [comment]
But we do tests on the github CI

**Comment by tuannn2** [comment]
The problem is fixed, I will close the issue.
