### ISSUE TITLE
Add a new value 'On Hold' to the Request Status of a CR and add a new filter 'Next/Last 15 days' to the agreed clearing date in advanced search

### ISSUE THREAD

**Issue by afsahsyeda** [eclipse-sw360/sw360#2051]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Request portlet changes:

- Add a new option 'On Hold' for the Request status dropdown in the edit page of CR
![image](https://github.com/eclipse-sw360/sw360/assets/115608771/ca29b92b-364a-4691-949c-3d8de100c05d)

- In advanced search bar, add new filters called 'Next 15 days' and 'Last 15 days' under the 'Agreed Clearing Date' filter.
<img width="143" alt="MicrosoftTeams-image (2)" src="https://github.com/eclipse-sw360/sw360/assets/115608771/42766573-a79e-45b3-a2ca-c1505f06567a">

**Comment by nikkuma7** [comment]
![image](https://github.com/eclipse-sw360/sw360/assets/49710817/3b9b364f-90c0-426f-b164-2059ca484725)
