### ISSUE TITLE
Package portlet not found 

### ISSUE THREAD

**Issue by tuannn2** [eclipse-sw360/sw360#2068]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

After merge [#1999 ](https://github.com/eclipse-sw360/sw360/pull/1999) 

I build the latest code on the main branch but didn't find the Package portlet.

We need making new Private_Pages_7_4_3_18_GA18.lar

**Comment by afsahsyeda** [comment]
Hi @tuannn2 ,

Have you tried this?

-  Click on the '+' icon

![image](https://github.com/eclipse-sw360/sw360/assets/115608771/ca0fba60-ae13-4d3d-8931-6bdd6e70b285)

- Search for 'Packages' and add the result in the Packages tab

![image](https://github.com/eclipse-sw360/sw360/assets/115608771/66b7861e-b57c-4ac4-86cf-157b69b78dba)

**Comment by tuannn2** [comment]
hi @afsahsyeda, 
I tried your way but I can't find the Portlet package.
I tried again and found it when configuring portlet or import lar file private PR #2069
![image](https://github.com/eclipse-sw360/sw360/assets/94596393/a9fcdbe5-fb78-40c7-a172-5d6155d37ba3)

For first time users of Package Portlet function, They need to configure portlet or can import lar file private in PR #2069

**Comment by afsahsyeda** [comment]
Yes, the first step would be to 'Add Page' in the 'Private Pages' section. Name the Page 'Packages' and place it below 'Components'. 
Next, we can navigate to the Packages portlet, which will be empty. Then, we can click on the '+' icon in the top right corner to add the 'Packages' page.
