### ISSUE TITLE
The component names with spaces are not searchable due to the conversion of space character to "%20" (URL Encoding)

### ISSUE THREAD

**Issue by afsahsyeda** [eclipse-sw360/sw360#2115]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description
Component names with space are not searchable via REST API after this PR #2043

**Comment by afsahsyeda** [comment]
- The space character is getting converted to "%20"(URL Encoding) due to which component names with space in between are not searchable.
- Previously, the name query would get decoded and then searched over the DB. But now this functionality is removed. For ex: search queries like "?name=%40angular%2Fanimations" would be read as "?name=@angular/animations". Now, "%40angular%2Fanimations" is read as "%40angular%2Fanimations" only since decoding of characters is removed. 
- However, enabling support to decoding characters would affect special characters like "+" which are interpreted as space in Java URL Decoding.

**Comment by JSurf** [comment]
See also https://github.com/eclipse-sw360/sw360/issues/2042#issuecomment-1961170045

any url encoded name is now broken, which breaks the official SW360 java client

**Comment by heliocastro** [comment]
@ag4ums ^^^
