### ISSUE TITLE
feat(Rest) : Releases attachment download is failing

### ISSUE THREAD

**Issue by keerthi-bl** [eclipse-sw360/sw360#2136]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Download attachment is not working with rest end point.

Response structure has changed from "_embedded" : { "sw360:attachments" : [] } to {'_embedded': {'sw360:attachmentDTOes': […

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by tuannn2** [comment]
Hi @keerthi-bl, 
I am using sw360 int branch Main (4666d876be224ef487a4e7751eed1b4398a33b8b).
I'm still using the donwload attachment functionality for projects, components, releases normally.

May I know which Endpoint you are using?

**Comment by tuannn2** [comment]
Hi @keerthi-bl, 
Can you change title issues? Because features Download attachment is working normally.

- On response structure has been changed to add field response detail for  Listing Attachment Information for Release, Component page in sw360-frontend

Is this change necessary?

**Comment by ag4ums** [comment]
@keerthi-bl, please create PR with the reverted changes

**Comment by keerthi-bl** [comment]
#2140 is the PR @ag4ums , already merged. Need to close this issue only.

**Comment by keerthi-bl** [comment]
Hi @tuannn2 : 
The end point is not failing actually. 

**{**.**  On response structure has been changed to add field response detail for Listing Attachment Information for Release, Component page in sw360-frontend}**

Its failing to the client who are accepting the key as **attachments** from the end point . So the above changes affect other clients who are using this end point. So its necessary to revert the changes. 

Please confirm, can we close this issue.

**Comment by keerthi-bl** [comment]
Closing the issue, expected functionality working fine.
