### ISSUE TITLE
User can't open mkdoc link  at the footer

### ISSUE THREAD

**Issue by KoukiHama** [eclipse-sw360/sw360#2189]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

[Reported the issue in this PR.](https://github.com/eclipse-sw360/sw360/pull/2182#issuecomment-1812002648)

#### How to reproduce

 SW360 Docs link at the footer is not working.

#### Screenshots

![image](https://github.com/eclipse-sw360/sw360/assets/39894802/23848688-e7d9-48a2-8317-0c55cc8a0c8c)

### Versions

* Last commit id on master:
* Operating System (lsb_release -a): [6be2c6f](https://github.com/eclipse-sw360/sw360/commit/6be2c6f791f9928362a419a2f61ba7142ce66cff)

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by KoukiHama** [comment]
@akshitjoshii

Did you use option -Dhelp-docs=true when you install sw360?

**Comment by akshitjoshii** [comment]
Hi @KoukiHama, I did not use this to build sw360.

**Comment by KoukiHama** [comment]
@akshitjoshii
OK, Thank you for your info. 
I can build mkdocs page with the option on latest SW360.
Therefore, I close this issue.
