### ISSUE TITLE
feat(rest): Create new endpoint to cancel all scheduled services in schedule tab.

### ISSUE THREAD

**Issue by nikkuma7** [eclipse-sw360/sw360#2237]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Create new endpoint to cancel all the schedule task. means if any numbers of schedule services are running and we can cancel all the task on single service call. 

Note: Users should have admin access.

#### Steps followed and expected result

Describe the steps followed by you and your expected results after following the steps.

**Comment by keerthi-bl** [comment]
@nikkuma7 : 
Please elaborate/describe issue in few words and also please mention which are all the scheduled services get affected - for better understanding.
