### ISSUE TITLE
Enable package portlet by default

### ISSUE THREAD

**Issue by ag4ums** [eclipse-sw360/sw360#2285]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Please describe your situation in few words here.

#### Steps followed and expected result

Enable package portlet by default with installation for sw360,

**Comment by ag4ums** [comment]
need to merge before release #2257

**Comment by KoukiHama** [comment]
I will review this.
