### ISSUE TITLE
Restriction on CR Creation for Projects with COTS Components Due to Attachment Type SRC Requirement

### ISSUE THREAD

**Issue by sameed20** [eclipse-sw360/sw360#2351]
### Description
PR: #2263 

Following the merging of this PR, users are not able to create (**CR**) for projects involving (**COTS**) components. The changes introduced in this PR restrict CR creation for projects without the attachment type SRC in their releases. However, it's important to note that the attachment type **SRC** is not applicable for COTS components,  which is making a challenge for users trying to initiate CR in such scenarios.

**Comment by afsahsyeda** [comment]
This PR has been reverted
