### ISSUE TITLE
VCS Validation of a component and sanitization of github URL's. Change CDX Importer logic accordingly.

### ISSUE THREAD

**Issue by afsahsyeda** [eclipse-sw360/sw360#2377]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

- User can put any URL in the VCS field during component creation/editing such as "ettp://a23". Only URLS starting with "https://" should be allowed.
- Once the request is submitted, a check should be carried out in the backend for VCS of github.com domain (later more domains like bitbucket, gitlab, google code can be taken up).- It should follow the format: https://github.com/supplier/name. URLs like these: `git+https://github.com/angular/angular.git#packages/animations` `git+ssh://git@github.com/constellation/escodegen` `git://github.com/lgalfaso/angular-dynamic-locale` should be sanitized before allowing in the DB to enable one VCS per component policy in SW360.
- Appropriate error to be thrown when the GitHub URL has missing parts like component name.
- This check should be introduced at the CDX Importer level as well (reuse the same sanitizeVCS function).

#### Steps followed and expected result

- This VCS Validation mechanism is essential for the SRC Upload service of releases to work correctly.

**Comment by michaelwildvarian** [comment]
While the source downloader only knows to deal with GitHub URL's for now, please do not reject other domains. That would completely break e.g. the import of Android packages.
