### ISSUE TITLE
How to enable https for sw360 application 18.1.0?

### ISSUE THREAD

**Issue by dineshr93** [eclipse-sw360/sw360#2562]
### Description

I am looking to enable https for sw360 18.1.0 web application (baremetal deploy)? Please is there any help/pointers to enable https from http? 
Thanks

**Comment by KoukiHama** [comment]
you can change it in liferay property file.

**Comment by dineshr93** [comment]
> you can change it in liferay property file.
Thanks !.  Do you see any change in following these procedures?
https://proliferay.com/configure-https-in-liferay-dxp-7-4-tomcat-9/
or 
https://help.liferay.com/hc/en-us/articles/360018410832-How-to-configure-HTTPS-in-Tomcat-for-Liferay-DXP-7-3

**Comment by KoukiHama** [comment]
Yes, you can do it by the URLs.


Step 4: Update portal-ext.properties

Update the server protocol in portal-ext.properties

web.server.protocol=https

**Comment by dineshr93** [comment]
> Yes, you can do it by the URLs.
> 
> −−−−−
> 
> Step 4: Update portal-ext.properties
> 
> Update the server protocol in portal-ext.properties
> 
> web.server.protocol=https

Hi @KoukiHama   I tried now. the site worked.  but however the data is not there. 
![image](https://github.com/user-attachments/assets/9c2445ab-f8cb-4a2a-8712-3a9b5e485d6e)

do we need to enable something between webapp and database?

**Comment by KoukiHama** [comment]
Did you set some test users?
SW360 version 18.1 (liferay) require to use postgres as managing users.

**Comment by dineshr93** [comment]
> Did you set some test users?

Its an existing instance with lot of existing data available already previous to enabling SSL @KoukiHama

**Comment by KoukiHama** [comment]
The https protocol and the database are basically unrelated.

Does the user you are using to log in belong to a group?

**Comment by dineshr93** [comment]
> Does the user you are using to log in belong to a group?
I too thought so. But when I rolled back the ssl related changes and re deployed via http I can see all the data 
![image](https://github.com/user-attachments/assets/2dd8abd1-5f91-468e-a279-018ba8e418f3)

**Comment by KoukiHama** [comment]
I am little confused about your results.

How did you connect postgres in portal-setup-wizard.properties or other property files.

Especially these parameters

>jdbc.default.driverClassName=org.postgresql.Driver
> jdbc.default.password=password
>jdbc.default.url=jdbc:postgresql://xxxxx:5432/lportal
> jdbc.default.username=postgres

**Comment by dineshr93** [comment]
> How did you connect postgres in portal-setup-wizard.properties or other property files.

my portal-setup-wizard.properties is
```js
admin.email.from.address=Dinesh.R@company.com
admin.email.from.name=Test Test
company.default.locale=en_US
company.default.time.zone=UTC
company.default.web.id=elektrobit.com
default.admin.email.address.prefix=Dinesh.R
jdbc.default.driverClassName=org.postgresql.Driver
jdbc.default.password=lportal
jdbc.default.url=jdbc:postgresql://localhost:5432/lportal
jdbc.default.username=lportal
liferay.home=/opt/liferay-ce-portal-7.4.3.18-ga18
setup.wizard.enabled=false
```

**Comment by dineshr93** [comment]
HI @KoukiHama  Thanks for your help 
I figured out that keeping both the connector works. I am disabling the first connector before as per https://proliferay.com/configure-https-in-liferay-dxp-7-4-tomcat-9/ thats why the webpage is working but data is not coming through 

```js
    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
            redirectPort="8443" URIEncoding="UTF-8" />
    <Connector
           protocol="org.apache.coyote.http11.Http11NioProtocol"
            port="443" redirectPort="8443"
            maxThreads="200"
           scheme="https" secure="true" SSLEnabled="true"
            keystoreFile="/home/name/domain-company-com.keystore" keystorePass="your_keystore_pass"
            clientAuth="false" sslProtocol="TLS"/>
```

but now it works ! Thanks
