### ISSUE TITLE
Current `main` branch seems to be broken

### ISSUE THREAD

**Issue by smrutis1** [eclipse-sw360/sw360#2630]
### Description

Most of the war deployment failing in current `main` (https://github.com/eclipse-sw360/sw360/commit/e3dccf3eea7f462d16ecf795e1e4b343afb9b751)

![image](https://github.com/user-attachments/assets/3187454f-094b-4e3c-b27a-de83ac798fab)

**Comment by heliocastro** [comment]
Something not add, as we not changed anything since 2 weeks.
@smrutis1 How are you deploying ?
And please, a request from my side, we evolved a log in the interfaces, we don't anymore push screenshots, but we can easily push a formatted text log. Next time, please use text format.

**Comment by heliocastro** [comment]
Just did a clean build and started as docker compose up. Tomcat manager says everything's clear.
We do need more details on how are you deploying things

**Comment by smrutis1** [comment]
> Something not add, as we not changed anything since 2 weeks. @smrutis1 How are you deploying ? And please, a request from my side, we evolved a lot in the interfaces, we don't anymore push screenshots, but we can easily push a formatted text log. Next time, please use text format.

I just copy the war files to tomcat `webapps`, not yet tried the docker one though. Seems like except `rest` all other war file deployment is failing. Attached the catalina log file for reference. 

[catalina_out.txt](https://github.com/user-attachments/files/17204123/catalina_out.txt)

**Comment by heliocastro** [comment]
This explains A LOT.
On the docker container, jar files are not inside the war, but in a shared directory, so, for that reason it never failed there.
@GMishx We should decide if we will support bare metal installation, if yes, I will prepare complete extra setup instructions.
